import torch
print("empty")
x = torch.empty(2, 3)
print(x)
print("rand")
x = torch.rand(2, 3)
print(x)
print("zeros")
x = torch.zeros(2, 3, dtype=torch.long)
print(x)
print("ones")
x = torch.ones(2, 3, dtype=torch.long)
print(x)
print("tensor")
x = torch.tensor([2, 3])
print(x)